// Create user
POST http://localhost:3001/register
Content-Type: application/json

{
    "name": "teste",
    "email": "messi1@gmail.com",
    "password": "1234567"
}

### // Login user
POST http://localhost:3001/session
Content-Type: application/json

{
    "email": "mirulandos@gmail.com",
    "password": "1234567s"
}

### // list users
GET http://localhost:3001/users


### 
DELETE http://localhost:3001/delete-user/mirulando@gmail.com


// ORDERS

// All orders
###
GET http://localhost:3001/orders


// Get Order specific
###
GET http://localhost:3001/orders/e3ab5e8b-da77-4d85-80ee-58aa7e1239a0


// Delete order specific
###
DELETE  http://localhost:3001/orders/e3ab5e8b-da77-4d85-80ee-58aa7e1239a0
 

###
POST  http://localhost:3001/create-order
Content-Type: application/json

{
    "orderId": "e3ab5e8b-da77-4d85-80ee-58aa7e1239a0",
    "name": "MidleWare",
    "date": "20/07 as 20:00 hr",
    "location": "Rua tupi guarani 240",
    "quantity": 3
}